package com.sellProject.dao;

import com.sellProject.dataobject.StockLogDo;

public interface StockLogDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon Nov 11 12:07:52 CST 2019
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon Nov 11 12:07:52 CST 2019
     */
    int insert(StockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon Nov 11 12:07:52 CST 2019
     */
    int insertSelective(StockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon Nov 11 12:07:52 CST 2019
     */
    StockLogDo selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon Nov 11 12:07:52 CST 2019
     */
    int updateByPrimaryKeySelective(StockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon Nov 11 12:07:52 CST 2019
     */
    int updateByPrimaryKey(StockLogDo record);
}